### ISSUE TITLE
Base pipe?

### ISSUE THREAD

**Issue by sckott** [fhdsl/sixtyfour#1]
https://www.tidyverse.org/blog/2023/04/base-vs-magrittr-pipe/

@seankross any sense for whether FH folks are generally running newer versions of R or not so much? 

If folks generally use 4.1 or greater, then we could use `|>`, but if not, then we'd probably want to stick with ` %>%`

thoughts?

**Comment by seankross** [comment]
Definitely a good thought, let's switch to the old pipe for compatibility's sake.

**Comment by sckott** [comment]
will do
